import { Workout, TargetArea } from '@/types/types';
import {
  Rest,
  TensAndTwos,
  AgilityCircles,
  AlternatingSupermans,
} from '@/components/Workouts';

export const workouts: Array<Workout> = [
  {
    id: 0,
    name: 'Rest',
    duration: 10,
    target: TargetArea.Rest,
    visual: <Rest />,
  },
  {
    id: 11,
    name: '10s and 2s',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 12,
    name: 'Agility Circles',
    duration: 6,
    target: TargetArea.Full,
    visual: <AgilityCircles />,
  },
  {
    id: 13,
    name: 'Alternating Supermans',
    duration: 6,
    target: TargetArea.Core,
    visual: <AlternatingSupermans />,
  },
  {
    id: 14,
    name: 'Balance Reaches',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 15,
    name: 'Bicycles',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 16,
    name: 'Burpees',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
  {
    id: 17,
    name: 'Cross-Body V-Ups',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 18,
    name: 'Crunches',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 19,
    name: 'Curtsy Lunges',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 20,
    name: 'Diagonal Lunges',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 21,
    name: 'Dive-Bomber Push-Ups',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 22,
    name: 'Double Crunches',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 23,
    name: 'Hello Dollies',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 24,
    name: 'Hightail Push-Ups',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 25,
    name: 'Jump Lunges',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 26,
    name: 'Jump Squats',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 27,
    name: 'Jumping Jacks',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
  {
    id: 28,
    name: 'Lateral Lunges',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 29,
    name: 'Lunges',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 30,
    name: 'Mountain Climbers',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
  {
    id: 31,
    name: 'Plank',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 32,
    name: 'Plank to Push-Up',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 33,
    name: 'Primal Step-Ups',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 34,
    name: 'Prisoners',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 35,
    name: 'Push-Up and Rotate',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 36,
    name: 'Push-Up Spiders',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 37,
    name: 'Push-Ups',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 38,
    name: 'Reverse Lunge and Rotate',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 39,
    name: 'Reverse Lunges',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 40,
    name: 'Shadow Boxing',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
  {
    id: 41,
    name: 'Side Plank',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 42,
    name: 'Skater Plyos',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 43,
    name: 'Sports Sprints',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
  {
    id: 44,
    name: 'Squats',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 45,
    name: 'Step-Up Squats',
    duration: 6,
    target: TargetArea.Lower,
    visual: <TensAndTwos />,
  },
  {
    id: 46,
    name: 'Surfers',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
  {
    id: 47,
    name: 'Swimmers',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 48,
    name: 'Toe Touches',
    duration: 6,
    target: TargetArea.Core,
    visual: <TensAndTwos />,
  },
  {
    id: 49,
    name: 'Triceps Dip and Reach',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 50,
    name: 'Triceps Dips',
    duration: 6,
    target: TargetArea.Upper,
    visual: <TensAndTwos />,
  },
  {
    id: 51,
    name: 'Worm Walkouts',
    duration: 6,
    target: TargetArea.Full,
    visual: <TensAndTwos />,
  },
];
